Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: simple-bank
      Version: "1.23"
      RoleArn: "arn:aws:iam::648824198004:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS"
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-0f3dae693c201c201
          - subnet-080a66ade72fa57d1
          - subnet-0683015a39d64df1b
        SecurityGroupIds:
          - sg-050506022ca3e9883 # access_anywhere
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
  EKSNodegroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      ClusterName: simple-bank
      NodeRole: "arn:aws:iam::648824198004:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup"
      ScalingConfig:
        MinSize: 0
        DesiredSize: 0
        MaxSize: 2
      Subnets:
        - subnet-0f3dae693c201c201
        - subnet-080a66ade72fa57d1
        - subnet-0683015a39d64df1b
